---
kind: Service
apiVersion: v1
metadata:
  name: demo
  namespace: default
  annotations:
    bal.io/job-orchestrator: "true"
  labels:
    run: demo
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    run: demo