---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-controller
  namespace: dummycontroller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-controller
rules:
- apiGroups: [""]
  resources:
  - services
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: go-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: go-controller
subjects:
- kind: ServiceAccount
  name: go-controller
  namespace: default

